spring:
  datasource:
    url: jdbc:postgresql://localhost:25432/test
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true